### ISSUE TITLE
Error running Install-Lab

### ISSUE THREAD

**Issue by RobertKozak** [PlagueHO/LabBuilder#203] opened 2016-04-18 19:40 UTC
Get-VMNetworkAdapter : Hyper-V encountered an error trying to access an object on computer 'ROBERTSP4' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that
the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
At C:\Program Files\WindowsPowerShell\Modules\LabBuilder\0.7.4.852\LabBuilder.psm1:5128 char:38
+         $ExistingManagementAdapter = Get-VMNetworkAdapter `
+                                      ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VMNetworkAdapter], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMNetworkAdapter

**Running as Admin and VMMS service is running**

**Running Windows 10 latest released version all windows updates done.**

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    10     0      10586  0

**PowerShell version**

    Name                           Value
    ----                           -----
    PSVersion                      5.0.10586.122
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.10586.122
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1

**Comment by PlagueHO** [comment] 2016-04-18 23:07
Hi @RobertKozak - That error has me scratching my head. The issue appears to be the VMMS service isn't running or isn't accessible, but that would mean Hyper-V wasn't running.

If you open Hyper-V manager, are you able to show all the Hyper-V Virtual Switches?
![2016-04-19_11-04-42](https://cloud.githubusercontent.com/assets/7589164/14622537/aa213ae8-061e-11e6-9e37-95206141870e.png)

Can you see one called: "DOMAIN.COM Lab Management" - where DOMAIN.COM is the LAB ID of the lab you're creating?

**Comment by RobertKozak** [comment] 2016-04-18 23:12
Yes I can see them.

    [0.00ms] PS C:\> get-service vmms

    Status   Name               DisplayName
    ------   ----               -----------
    Running  vmms               Hyper-V Virtual Machine Management

    [15.62ms] PS C:\> get-vmswitch

    Name                                SwitchType NetAdapterInterfaceDescription
     ----                                ---------- ------------------------------
     External                            External   Surface Ethernet Adapter
    WIFI Switch
    DevOps.COM Lab Management           Private
    DevOps.COM General Purpose Internal Private
    DevOps.COM Domain Private Site A    Private
    DevOps.COM Domain Private Site B    Private
    DevOps.COM Domain Private Site C    Private

    [9.00s] PS C:\>

**Comment by RobertKozak** [comment] 2016-04-18 23:57
Here is the full verbose logging after trying it again. Took 18 mins:
[31.45ms] PS Server2016> Install-Lab -ConfigPath D:\Labs\Server2016\Sample_WS2016TP4_DCandDHCPOnly.xml -verbose
    VERBOSE: Initializing Lab Folders.
    VERBOSE: Creating LabPath folder 'D:\Labs\Server2016\DEVOPS.COM' for Lab.
    VERBOSE: Creating VHDParentPath folder 'D:\Labs\Server2016\DEVOPS.COM\Virtual Hard Disk Templates' for Lab.
    VERBOSE: Creating ResourcePath folder 'D:\Labs\Server2016\DEVOPS.COM\Resource' for Lab.
    VERBOSE: Initializing Hyper-V Components.
    Get-VMNetworkAdapter : Hyper-V encountered an error trying to access an object on computer 'ROBERTSP4' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that
    the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
    At C:\Program Files\WindowsPowerShell\Modules\labbuilder\0.7.4.852\LabBuilder.psm1:5128 char:38
    +         $ExistingManagementAdapter = Get-VMNetworkAdapter `
    +                                      ~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (:) [Get-VMNetworkAdapter], VirtualizationException
        + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMNetworkAdapter

    VERBOSE: Skip building VM template VHD file 'D:\Labs\Server2016\VHDFiles\Windows Server 2016 TP4 Datacenter Core.vhdx' for 'Windows Server 2016 TP4 Datacenter CORE' because it already exists.
    VERBOSE: Skip building VM template VHD file 'D:\Labs\Server2016\VHDFiles\Nano Server 2016 TP4 Basic.vhdx' for 'Nano Server 2016 TP4 Basic' because it already exists.
    VERBOSE: Copying template source VHD 'D:\Labs\Server2016\VHDFiles\Windows Server 2016 TP4 Datacenter Core.vhdx' to 'D:\Labs\Server2016\DEVOPS.COM\Virtual Hard Disk Templates\Windows Server 2016 TP4 Datacenter Core.vhdx'.
    VERBOSE: Optimizing parent VHD 'D:\Labs\Server2016\DEVOPS.COM\Virtual Hard Disk Templates\Windows Server 2016 TP4 Datacenter Core.vhdx'.
    VERBOSE: Setting parent VHD 'D:\Labs\Server2016\DEVOPS.COM\Virtual Hard Disk Templates\Windows Server 2016 TP4 Datacenter Core.vhdx' as readonly.
    VERBOSE: Copying template source VHD 'D:\Labs\Server2016\VHDFiles\Nano Server 2016 TP4 Basic.vhdx' to 'D:\Labs\Server2016\DEVOPS.COM\Virtual Hard Disk Templates\Nano Server 2016 TP4 Basic.vhdx'.
    VERBOSE: Optimizing parent VHD 'D:\Labs\Server2016\DEVOPS.COM\Virtual Hard Disk Templates\Nano Server 2016 TP4 Basic.vhdx'.
    VERBOSE: Setting parent VHD 'D:\Labs\Server2016\DEVOPS.COM\Virtual Hard Disk Templates\Nano Server 2016 TP4 Basic.vhdx' as readonly.
    ThrowException : The template 'Windows Server 2016 TP4 Datacenter CORE' specified in VM 'DEVOPS.COM DC01' could not be found.
    At C:\Program Files\WindowsPowerShell\Modules\labbuilder\0.7.4.852\LabBuilder.psm1:3138 char:13
    +             ThrowException @ExceptionParameters
    +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [ThrowException], Exception
        + FullyQualifiedErrorId : VMTemplateNotFoundError,ThrowException

    ThrowException : The template 'Windows Server 2016 TP4 Datacenter CORE' specified in VM 'DEVOPS.COM DHCP01' could not be found.
    At C:\Program Files\WindowsPowerShell\Modules\labbuilder\0.7.4.852\LabBuilder.psm1:3138 char:13
    +             ThrowException @ExceptionParameters
    +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [ThrowException], Exception
        + FullyQualifiedErrorId : VMTemplateNotFoundError,ThrowException

    VERBOSE: Creating VM 'DEVOPS.COM DC01'.
    VERBOSE: Creating Differencing Boot disk 'D:\Labs\Server2016\DEVOPS.COM\DEVOPS.COM DC01\Virtual Hard Disks\DEVOPS.COM DC01 Boot Disk.vhdx' for VM 'DEVOPS.COM DC01'.
    Initialize-LabVM : Cannot validate argument on parameter 'ParentPath'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
    At C:\Program Files\WindowsPowerShell\Modules\labbuilder\0.7.4.852\LabBuilder.psm1:5192 char:9
    +         Initialize-LabVM `
    +         ~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidData: (:) [Initialize-LabVM], ParameterBindingValidationException
        + FullyQualifiedErrorId : ParameterArgumentValidationError,Initialize-LabVM

    VERBOSE: The Lab 'Sample_WS2016TP4_DCandDHCPOnly' has been installed into folder 'D:\Labs\Server2016\DEVOPS.COM'.
    [18.80m] PS Server2016>

**Comment by PlagueHO** [comment] 2016-04-18 23:58
That has me scratching my head.

The error is in this line:
```powershell
        $ExistingManagementAdapter = Get-VMNetworkAdapter `
            -ManagementOS `
            -Name $ManagementSwitchName
```

$ManagementSwtichName is set to 'DevOps.COM Lab Management'

What happens when you issue these commands:
```powershell
$ManagementSwtichName = 'DevOps.COM Lab Management'
        $ExistingManagementAdapter = Get-VMNetworkAdapter `
            -ManagementOS `
            -Name $ManagementSwitchName
```

**Comment by RobertKozak** [comment] 2016-04-18 23:59
[18.80m] PS Server2016> $ManagementSwtichName = 'DevOps.COM Lab Management'
    >>         $ExistingManagementAdapter = Get-VMNetworkAdapter `
    >>             -ManagementOS `
    >>             -Name $ManagementSwitchName
    Get-VMNetworkAdapter : Hyper-V encountered an error trying to access an object on computer 'ROBERTSP4' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that
    the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
    At line:2 char:38
    +         $ExistingManagementAdapter = Get-VMNetworkAdapter `
    +                                      ~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (:) [Get-VMNetworkAdapter], VirtualizationException
        + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMNetworkAdapter

    [6.70s] PS Server2016>

**Comment by RobertKozak** [comment] 2016-04-19 00:01
Maybe I have my Hyper-V setup wrong? Should I uninstall Hyper-V and Add it back? Will it setup my external switch properly or do I need to do that again before trying LabBuilder?

**Comment by PlagueHO** [comment] 2016-04-19 00:01
You're running as a Local admin on the machine Hyper-V host?

**Comment by RobertKozak** [comment] 2016-04-19 00:02
yes I am a local admin. My Surface Pro 4 is joined to a Domain but I am local admin on it.

**Comment by PlagueHO** [comment] 2016-04-19 00:03
I can't see that you've got Hyper-V setup wrong - at least I don't think you could have. Do you want to chat on the Gitter channel for LabBuilder - might be easier :) https://gitter.im/PlagueHO/LabBuilder?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by PlagueHO** [comment] 2016-04-30 00:30
I think this one is solved. I'll close it.

**Closed by PlagueHO** 2016-04-30 00:30 UTC
Labels: In Process

**Comment by imessage357** [comment] 2017-02-25 01:22
what was the fix?

**Comment by PlagueHO** [comment] 2017-02-25 01:27
Hi @imessage357 - we couldn't identify the cause of the problem. It looked like a bad Hyper-V install, but nothing would fix it. I think from memory he switched to a using a different PC. But I could be completely wrong (it was a while back now). Are you having the same errors?
